export const NAMES = [
  '24x7 Innovation Labs',
  'ABCO',
  'Accenture',
  'Accolite',
  'Adobe',
  'Airtel',
  'Almabase',
  'Amadeus Labs',
  'Amazon',
  'Amdocs',
  'American Express',
  'Apple',
  'AQR Capital',
  'Arcesium',
  'Aricent',
  'Arista Networks',
  'Atlassian',
  'Axis Bank',
  'BankBazaar',
  'Belzabar',
  'Bidgely',
  'Bloomberg',
  'Blue Yonder',
  'BNY Mellon',
  'Boomerang Commerce',
  'Brocade',
  'BrowserStack',
  'Cadence India',
  'CarWale',
  'Cavisson System',
  'CGI',
  'Chronus',
  'Cisco',
  'Citicorp',
  'Citrix',
  'Cloudera',
  'CodeBrew',
  'CodeNation',
  'Cognizant',
  'CouponDunia',
  'Culture Edge',
  'Cure Fit',
  'D.E. Shaw',
  'DailyHunt',
  'Dell',
  'Deloitte',
  'Deutsche Bank',
  'Directi',
  'Disney+ Hotstar',
  'Dr Reddy\'s',
  'Drishti-Soft',
  'Dunzo',
  'eBay',
  'Epic Systems',
  'Expedia',
  'Fab.com',
  'Facebook',
  'FactSet',
  'FinancePeer',
  'Fischer Jordan',
  'Flipkart',
  'Fractal Analysis',
  'Freecharge',
  'Freshokartz',
  'GE',
  'Goldman Sachs',
  'Google',
  'GreyOrange',
  'Grofers',
  'Groupon',
  'HCL',
  'Hike',
  'Honeywell',
  'Housing.com',
  'HSBC',
  'Huawei',
  'HunanAsset',
  'IBM',
  'IgniteWorld',
  'Infinera',
  'InfoEdge',
  'Informatica',
  'Infosys',
  'InMobi',
  'Instabase',
  'Intel',
  'Intuit',
  'ITC',
  'Jabong',
  'John Deere',
  'Junglee Games',
  'Juniper Networks',
  'Juspay',
  'KLA Tencor',
  'Knowlarity',
  'Komli Media',
  'Kritikal Solutions',
  'Kuliza',
  'LinkedIn',
  'Lybrate',
  'Mahindra Comviva',
  'MakeMyTrip',
  'Mallow Technologies',
  'MAQ Software',
  'MasterCard',
  'MathWorks',
  'Media.net',
  'Medlife',
  'MetLife',
  'Microsoft',
  'Mindfire Solutions',
  'Mobicip',
  'Monotype Solutions',
  'Moonfrog Labs',
  'Morgan Stanley',
  'Motlay',
  'Myntra',
  'Nagarro',
  'National Instruments',
  'NatWest',
  'Navyug Infosolutions',
  'Nearbuy',
  'Neosoft',
  'Netskope',
  'Newzera',
  'NPCI',
  'Nutanix',
  'NVIDIA',
  'Oats Systems',
  'Okta',
  'Ola Cabs',
  'One97',
  'Open Solutions',
  'Opera',
  'Oracle',
  'Oxigen Wallet',
  'Oyo Rooms',
  'PayPal',
  'Paytm',
  'PayU',
  'Philips',
  'PhonePe',
  'PlaySimple',
  'Polycom',
  'Practo',
  'PropTiger',
  'PubMatic',
  'Qualcomm',
  'Quikr',
  'Raam Group (Management)',
  'Radisys',
  'Redbus',
  'Rivigo',
  'Rockstand',
  'Salesforce',
  'Samsung',
  'SAP Labs',
  'Sapient',
  'Schlumberger',
  'Service Now',
  'Siemens Health',
  'Snapdeal',
  'Sprinklr',
  'Streamoid Technologies',
  'Swiggy',
  'Synopsys',
  'Target Corporation',
  'Taxi4Sure',
  'TCS',
  'Tejas Network',
  'Teradata',
  'Tesco',
  'Texas Instruments',
  'ThoughtWorks',
  'Times Internet',
  'TinyOwl',
  'Twitter',
  'Uber',
  'Udaan',
  'Unisys',
  'United Health Group',
  'Veritas',
  'Visa',
  'Vizury Interactive Solutions',
  'VMware',
  'Walmart',
  'Warner Bros. Discovery',
  'Wells Fargo',
  'Western Digital',
  'Wipro',
  'Wooker',
  'Xome',
  'Yahoo',
  'Yatra.com',
  'Yodlee Infotech',
  'Zillious',
  'Zoho',
  'Zomato',
  'Zopper',
  'Zycus',
];