name: Deploy Internito to EC2 automatically

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and Deploy
    run: |
      ssh -o StrictHostKeyChecking=no ubuntu@13.201.189.137 << 'EOF'
        cd internito
        GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key" git pull origin main
        cd client
        npm install
        npm run build
        sudo rm -rf /var/www/html/*
        sudo cp -r build/* /var/www/html/
        cd ../api
        npm install
        pm2 restart all
      EOF

